#!/bin/bash -xe

# Warning: this script is not supposed to be run on real system,
# as it will not clean up after itself.
# Use it only in ephemeral environments, such as Travis CI.

source $(dirname "$0")/env.sh

mkdir -p build
mount --bind build build
pushd build

curl -L ${ISO_URL} -o ${ISO_FN}
curl -L ${FRTCP_URL} -o ${FRTCP_FN}
curl -L ${GLIBC_URL} -o ${GLIBC_FN}
curl -L ${LNCR_URL} -o ${LNCR_ZIP}

unzip ${LNCR_ZIP} ${LNCR_FN}

mkdir isofs
mount -t iso9660 -o loop,ro ${ISO_FN} isofs
unsquashfs -f -d livefs ./isofs/LiveOS/rootfs.img

mount --bind livefs livefs

pushd livefs
mount -t proc /proc proc/
mount -t sysfs /sys sys/
mount --bind /dev dev/
mount --bind /run run/
mount -t tmpfs /tmp tmp/
mount --bind /etc/resolv.conf etc/resolv.conf
popd

mkdir rootfs
mount --bind rootfs rootfs
mount --bind rootfs livefs/mnt

cat <<EOF | chroot livefs /bin/bash -xe -
pacman-key --init
pacman-key --populate
pacman -Sy archlinux-keyring --noconfirm
basestrap -G -M -c /mnt ${PAC_PKGS}
EOF

echo "LANG=en_US.UTF-8" >> rootfs/etc/locale.conf
sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" rootfs/etc/locale.gen
sed -i -e "s/#IgnorePkg   =/IgnorePkg   = fakeroot/" rootfs/etc/pacman.conf
cp ${FRTCP_FN} ${GLIBC_FN} rootfs/

cat <<EOF | chroot livefs artix-chroot /mnt /bin/bash -xe -
locale-gen
pacman -U /${FRTCP_FN} /${GLIBC_FN} --noconfirm
EOF

echo "# This file was automatically generated by WSL. \
To stop automatic generation of this file, remove this line." > rootfs/etc/resolv.conf
rm -f rootfs/${FRTCP_FN} rootfs/${GLIBC_FN} 

tar zcpf rootfs.tar.gz -C rootfs .
zip Artix-${EDITION}.zip ${LNCR_FN} rootfs.tar.gz
