name: Build rootfs.tar.gz

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
  - cron: "0 0 * * *"

jobs:

  build_icon:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: .\build_icon.ps1
    - uses: actions/upload-artifact@v3
      with:
        name: wsldl
        path: Artix.exe

  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: ./download.sh
    - uses: actions/upload-artifact@v3
      with:
        name: download
        path: download/

  build:
    runs-on: ubuntu-latest
    needs:
     - download
     - build_icon

    strategy:
      fail-fast: false
      matrix:
        include:
        - edition: openrc
          extra_pkgs: openrc elogind-openrc
        - edition: runit
          extra_pkgs: runit elogind-runit
        - edition: s6
          extra_pkgs: s6-base elogind-s6
        - edition: dinit
          extra_pkgs: dinit elogind-dinit

    env:
      EDITION: ${{ matrix.edition }}
      EXTRA_PKGS: ${{ matrix.extra_pkgs }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: download
          path: download/
      - uses: actions/download-artifact@v3
        with:
          name: wsldl
          path: download/
      - run: sudo -E ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Artix-${{ matrix.edition }}
          path: out/Artix-${{ matrix.edition }}.zip

  post_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: |
            download
            wsldl

  publish:
    runs-on: ubuntu-latest
    needs: post_build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v3
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: latest
          files: Artix-*/Artix-*.zip
          prerelease: false
